-- TODO. Oracle 创建Sequence
-- INCREMENT BY 50 返回区间ID范围，在其后50ID均可用
-- NOCYCLE  不循环，直到最大值截至
-- NOORDER  不保证获取序列值的顺序，提高集群并发性能
-- CACHE 20 预先缓存20个序列值，如果DB挂掉导致缓存丢失，序列会出现挑号
CREATE SEQUENCE T_USERS_SEQ INCREMENT BY 50 MINVALUE 1 MAXVALUE 9999999999999 NOCYCLE CACHE 20 NOORDER;

-- 获取下一个ID值，无法获取则报错
select t_users_seq.nextval from dual;

-- CURRVAL只属于当前Session，具有会话隔离
-- CURRVAL必须在当前session调用NEXTVAL后才能用
SELECT T_USERS_SEQ.CURRVAL FROM DUAL;


-- TODO. SQL Server 创建Sequence
CREATE SEQUENCE JOB_INSTANCE_SEQ START WITH 0 MINVALUE 0 MAXVALUE 999999999999 NO CACHE NO CYCLE;

-- 获取下一个值
SELECT NEXT VALUE FOR JOB_INSTANCE_SEQ;

-- 直接在插入时获取
INSERT INTO JOB_INSTANCE (ID, NAME) VALUES (NEXT VALUE FOR JOB_INSTANCE_SEQ, 'test');

-- 直接绑定到ID默认值
CREATE TABLE JOB_INSTANCE (
    ID BIGINT DEFAULT NEXT VALUE FOR JOB_INSTANCE_SEQ,
    NAME VARCHAR(50)
);
INSERT INTO JOB_INSTANCE (NAME) VALUES ('abc');